[global]
# info = [ {tag="mameversion", value="0229"} ]
mraauthor=["jotego","atrac17"]

[features]
# ddr = true
#beta = true
# qsound=true
debug=true
# NVRAM = 64kB+10kB+1 byte
nvram = 75777

[parse]
sourcefile="segas16b.cpp"
# Games with S16A parents need explicit listing
# the description is used to make the alternate folders
parents= [
    {name="shinobi", description="Shinobi"},
    {name="afighter", description="Action Fighter"},
    {name="sdi", description="SDI"},
    {name="tetris", description="Tetris"}
]

[parse.skip]
descriptions = [ "16A", "Taito" ]
setnames = [ "lockonph" ]
# bootlegs = true # do not process bootlegs

[buttons]
core=4 # max number of buttons supported by the core

[rbf]
name="jts16b"
# dev = [
#     { dev="fd1094", rbf="jts16a2" },
#     { dev="8751", rbf="jts16a1"}
# ]

[dipsw]
delete = [ "Unused", "Unknown" ]
# base = 16

[header]
len=32
fill=0
dev = [
    { byte=0x10, dev="fd1089a", value=1 },
    { byte=0x10, dev="fd1089b", value=2 },
    { byte=0x11, dev="fd1094",  value=1 },
    { byte=0x12, dev="mc8123",  value=1 },
    { byte=0x13, dev="i8751",   value=1 }
]
machine = [
    { machine="riotcity", byte=0x18, value=4 },
    { machine="goldnaxe", byte=0x18, value=4 },
    { machine="eswat",    byte=0x18, value=4 }
]

# Sample header data
# data=[
#     { pointer=8,    data=[0xff, 0x43, 0x34] },
#     { pointer=0x10, data=[0xca, 0xfe] }
# ]


[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu",       width=16, reverse=true },
    { name="mcu",           start=$MCU_START, len=0x1000 },
    { name="soundcpu",      start=$BA1_START },
    { name="gfx1",          start=$BA2_START, frac={ bytes=1, parts=4}, sort_byext=true },
    { name="sprites",       start=$BA3_START, width=16, reverse=true },
    { name="maincpu:key",   start=$MAINKEY_START, len=0x2000 },
    { name="soundcpu:key",  start=$SNDKEY_START, len=0x2000 },
    { name="fd1089",        start=$FD1089_START },
    { name="plds",          skip=true }
]
# { name="myregion", reorder=[3,2,1,0] } # reorder files inside a region
order = [
    "maincpu", "soundcpu", "gfx1",
    "sprites", "mcu", "maincpu:key", "soundcpu:key"
]
splits = [
    { machine="riotcity", region="sprites", offset=0x100000 },
    { machine="goldnaxe", region="sprites", offset=0x100000 },
    { setname="eswat",    region="sprites", offset=0x100000 },
    { setname="mvp",      region="sprites", offset=0x100000 },
    { machine="ultracin", region="sprites", offset=0x100000 },
    # Do not split
    { setname="eswatj1", offset=0  },
    { setname="eswatj1d", offset=0 }
]
